### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by skskgrowl** [neu-vi/HOI-Diff#1]
Thank you for your excellent work, when will you release the training code?

**Comment by ymingxie** [comment]
Thank you for your interest in our work! The release time is expected before Feb. 2024 if things work all the best :).

Thanks,
Yiming

**Comment by MuHe97** [comment]
Thank you for your excellent work! I note that the code for your project is currently unpublished, and I understand that it may not be immediately available. However, I would very much like to have access to your dataset if possible.

**Comment by Zhongan-Wang** [comment]
Hello, I am very happy to see your work. It seems that your training code has not been released. When could we see your training code?
