### ISSUE TITLE
Error caused by ffmpeg path error

### ISSUE THREAD

**Issue by leeyiding** [neu-vi/HOI-Diff#11]
https://github.com/neu-vi/HOI-Diff/blob/78800b55e8308aa6827ba84a4192a2183e64a6d6/data_loaders/behave/utils/plot_script.py#L5

In your code, you specify your local ffmpeg path, but in my environment, the ffmpeg installation path is located in `/usr/bin/ffmpeg`. If you do not modify it here, it will cause a running error. It is recommended that you explain it in README, or provide configuration options to specify the ffmpeg path.

**Comment by xiaogangpeng** [comment]
Thanks for your advice, we've updated the README.
