### ISSUE TITLE
it cannot works as the project's provided page

### ISSUE THREAD

**Issue by MuHe97** [neu-vi/HOI-Diff#12]
First, thank you for developing and sharing this project; it has provided tremendous value to the community. I encountered an issue while attempting to replicate the project and hope to receive your assistance or guidance.
During the process of replicating the project, I noticed that when a person is holding an object in their hands, the position of these objects is unstable and continuously flickers, which is completely different from the effects shown on the project's provided page. My environment has been fully deployed as required by the project, and no additional bugs have occurred during operation. Is this situation normal? If necessary, I can provide more log information or screenshots. I really hope to get your help, thank you! Here is what I got.

https://github.com/neu-vi/HOI-Diff/assets/100480801/c04d6bda-47d6-40a2-9cbd-0f94072b9265

https://github.com/neu-vi/HOI-Diff/assets/100480801/43ca96e4-823a-4347-ac38-adb556161176

**Comment by etach-qs** [comment]
I'm having the same problem.
