### ISSUE TITLE
Some bugs due to the codes of HumanML3D.

### ISSUE THREAD

**Issue by qinghuannn** [neu-vi/HOI-Diff#15]
There are some bugs in the codes of HumanML3D as metioned in https://github.com/EricGuo5513/HumanML3D/issues/119#issue-2092049330. 

And I noticed that the dataset preprocessing codes used in the current codes of this repo are based on HumanML3D and have the same bugs in https://github.com/neu-vi/HOI-Diff/blob/main/utils/common/skeleton.py.

Will the authors fix it?

**Comment by xiaogangpeng** [comment]
Thank you for pointing this out, but it is too late to retrain all models using the updated pose representation. We have provided instructions on how to preprocess the raw behavioral data, so if you don't mind, you can preprocess the data again.
