### ISSUE TITLE
Sampling points of objects

### ISSUE THREAD

**Issue by erikbr01** [neu-vi/HOI-Diff#16]
Hi there, are there any details on how you choose the 512 points that represent the object point clouds? This seems to be missing in the preprocessing code?

**Comment by xiaogangpeng** [comment]
Hi, we randomly sampled 512 points: 
```
replace = False if len(obj_points) > 512 else True
o_choose = np.random.choice(len(obj_points), 512, replace=replace)
o_choose = np.sort(o_choose)
```
