### ISSUE TITLE
Hand or Wrist in affordance data?

### ISSUE THREAD

**Issue by yw0208** [neu-vi/HOI-Diff#27]
Hi,
I am a little confused about the affordance data. There is no hand in the 263-length joint vector.  But in the paper, you point out that the affordance data includes hands.
So my question: Are the hand labels in affordance data wrist labels? 
Your reply will be very helpful.

**Comment by xiaogangpeng** [comment]
Yes, in the affordance data, the term 'hands' refers to the wrist joints. We will clarify this more explicitly in both the paper and the README.
