### ISSUE TITLE
preprocess motion data from scratch

### ISSUE THREAD

**Issue by mengqing0312** [neu-vi/HOI-Diff#4]
Thank you for your excellent work. 
Could you please tell me what the numbers in sequencename.npy in the beiave_t2m dataset mean, for example, "Date 01 Sub01 backpack_back_5. npy"? 
I tried to preprocess motion data from scratch, but I am not sure which sub segments in beiave_t2m are from the original smpl_fit_all. npz. Can you provide the corresponding information? 
Thank you for your answer.

**Comment by xiaogangpeng** [comment]
Sorry for the late reply. We split the original motion sequence by our annonated data 'utils/action_label.json'. The details about how to split the data and preprocess the BEHAVE are updated in the 'utils/README.md'. Feel free to ask us if you have any question.
